vim.keymap.set("n", "gd", vim.lsp.buf.definition)
vim.keymap.set("n", "gD", vim.lsp.buf.declaration)
vim.keymap.set("n", "grr", vim.lsp.buf.references)
vim.keymap.set("n", "grn", vim.lsp.buf.rename)
vim.keymap.set("n", "K", vim.lsp.buf.hover)

vim.keymap.set("n", "]d", vim.diagnostic.goto_next)
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev)
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float)

vim.keymap.set("n", "<C-S-Down>", ":m .+1<CR>==", { silent = true })
vim.keymap.set("n", "<C-S-Up>", ":m .-2<CR>==", { silent = true })
vim.keymap.set("i", "<C-S-Down>", "<Esc>:m .+1<CR>==gi", { silent = true })
vim.keymap.set("i", "<C-S-Up>", "<Esc>:m .-2<CR>==gi", { silent = true })
vim.keymap.set("v", "<C-S-Down>", ":m '>+1<CR>gv=gv", { silent = true })
vim.keymap.set("v", "<C-S-Up>", ":m '<-2<CR>gv=gv", { silent = true })

vim.api.nvim_create_user_command("Discard", function()
  vim.fn.system({ "git", "restore", "--", vim.fn.expand("%:p") })
  vim.cmd("edit!")
end, {})
