[mgr]
show_hidden = true
ratio = [3, 4, 13]

[opener]
leaf = [
	{ run = "leaf %s", block = true, desc = "Leaf" },
]

[open]
prepend_rules = [
	{ url = "*.md", use = ["leaf", "edit"] },
]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
group = "git"
